# Generated by Django 4.2.17 on 2025-01-16 09:22

import re

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cloud_file", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filestorage",
            name="comment",
            field=models.CharField(blank=True, null=True, verbose_name="Mark"),
        ),
        migrations.AlterField(
            model_name="filestorage",
            name="file_path",
            field=models.FileField(
                upload_to="uploads/",
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[-a-zA-Z0-9_]+\\Z"),
                        "Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.",
                        "invalid",
                    ),
                    django.core.validators.MaxLengthValidator(
                        limit_value=100,
                        message="Check the characters quantity. Max quantity of characters is 100",
                    ),
                    django.core.validators.MinValueValidator(
                        limit_value=3,
                        message="Check the characters quantity. Max quantity of characters is 100",
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="filestorage",
            name="last_downloaded",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date download"
            ),
        ),
        migrations.AlterField(
            model_name="filestorage",
            name="original_name",
            field=models.CharField(max_length=100, verbose_name="File name"),
        ),
        migrations.AlterField(
            model_name="filestorage",
            name="size",
            field=models.PositiveIntegerField(verbose_name="File weight"),
        ),
        migrations.AlterField(
            model_name="filestorage",
            name="upload_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date upload"),
        ),
    ]
