# Generated by Django 4.2.17 on 2025-01-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("cloud_user", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="userregister",
            new_name="activated_index",
            old_name="activated_indx",
        ),
        migrations.AlterField(
            model_name="userregister",
            name="email",
            field=models.EmailField(
                help_text="email address", max_length=254, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="userregister",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="%(class)s_groups",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AlterField(
            model_name="userregister",
            name="is_activated",
            field=models.BooleanField(
                default=False,
                help_text="Part of the user registration. Message is sending to the email. В сообщении ссылка для подтверждения пользователя.",
                verbose_name="After activation",
            ),
        ),
        migrations.AlterField(
            model_name="userregister",
            name="send_messages",
            field=models.BooleanField(
                default=False,
                help_text="Part is registration of new user.It is message sending to user's email. User indicates his email at the registrations moment.",
                verbose_name="Слать оповещение",
            ),
        ),
        migrations.AlterField(
            model_name="userregister",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="%(class)s_user_permissions",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
    ]
