# Generated by Django 4.2.17 on 2025-01-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cloud_user", "0002_rename_activated_indx_activated_index_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userregister",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="last name"
            ),
        ),
    ]
