# Generated by Django 4.2.17 on 2025-01-12 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cloud_user", "0003_alter_userregister_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userregister",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="first name"
            ),
        ),
    ]
