# Generated by Django 4.2.17 on 2025-01-16 09:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cloud_user", "0004_alter_userregister_first_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userregister",
            name="is_superuser",
        ),
        migrations.AlterField(
            model_name="userregister",
            name="email",
            field=models.EmailField(
                help_text="email address",
                max_length=254,
                unique=True,
                validators=[django.core.validators.EmailValidator()],
            ),
        ),
    ]
