# Generated by Django 4.2.17 on 2025-01-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cloud_user", "0005_remove_userregister_is_superuser_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userregister",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user has all permissions without explicitly assigning them.",
                verbose_name="superuser status",
            ),
        ),
        migrations.AlterField(
            model_name="userregister",
            name="email",
            field=models.EmailField(
                help_text="email address", max_length=254, unique=True
            ),
        ),
    ]
