# Generated by Django 4.2.17 on 2025-02-07 04:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cloud_user", "0007_alter_userregister_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userregister",
            name="password",
            field=models.BinaryField(
                help_text="Password of user",
                max_length=128,
                validators=[
                    django.core.validators.MinLengthValidator(3),
                    django.core.validators.MaxLengthValidator(128),
                ],
                verbose_name="password",
            ),
        ),
    ]
