# Generated by Django 4.2.17 on 2025-02-07 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cloud_user", "0008_alter_userregister_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userregister",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
    ]
